import type { Product, User, Order } from "./types"

export const mockProducts: Product[] = [
  {
    _id: "1",
    name: "Classic Silk Hijab",
    description:
      "Premium quality silk hijab perfect for everyday wear. Soft, breathable, and available in multiple colors.",
    price: 29.99,
    images: ["/soft-silk-hijab.png", "/placeholder-hatu8.png"],
    stock: 50,
    featured: true,
    colors: ["Black", "Navy", "Cream", "Rose Gold"],
    sizes: ["Regular", "Large"],
    material: "Premium Silk",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "2",
    name: "Cotton Jersey Hijab",
    description: "Comfortable cotton jersey hijab ideal for daily activities. Stretchy and easy to style.",
    price: 19.99,
    images: ["/neutral-hijab.png", "/cotton-hijab-styling.png"],
    stock: 75,
    featured: true,
    colors: ["White", "Gray", "Beige", "Light Pink"],
    sizes: ["Regular", "Large"],
    material: "Cotton Jersey",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "3",
    name: "Chiffon Evening Hijab",
    description: "Elegant chiffon hijab perfect for special occasions. Lightweight with a beautiful drape.",
    price: 39.99,
    images: ["/elegant-chiffon-hijab.png", "/draped-chiffon-hijab.png"],
    stock: 30,
    featured: false,
    colors: ["Emerald", "Burgundy", "Gold", "Deep Blue"],
    sizes: ["Regular", "Large"],
    material: "Chiffon",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "4",
    name: "Modal Blend Hijab",
    description: "Soft modal blend hijab with excellent breathability. Perfect balance of comfort and style.",
    price: 24.99,
    images: ["/earth-tone-hijab.png", "/modal-hijab-fabric-texture.png"],
    stock: 60,
    featured: true,
    colors: ["Olive", "Dusty Rose", "Charcoal", "Ivory"],
    sizes: ["Regular", "Large"],
    material: "Modal Blend",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "5",
    name: "Printed Georgette Hijab",
    description: "Beautiful printed georgette hijab with intricate patterns. Adds elegance to any outfit.",
    price: 34.99,
    images: ["/floral-georgette-hijab.png", "/georgette-hijab-pattern.png"],
    stock: 25,
    featured: false,
    colors: ["Floral Blue", "Paisley Green", "Abstract Black"],
    sizes: ["Regular", "Large"],
    material: "Georgette",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "6",
    name: "Bamboo Fiber Hijab",
    description: "Eco-friendly bamboo fiber hijab. Naturally antibacterial and incredibly soft.",
    price: 27.99,
    images: ["/bamboo-hijab-natural.png", "/bamboo-hijab-texture.png"],
    stock: 40,
    featured: true,
    colors: ["Natural", "Sage Green", "Soft Brown", "Pearl White"],
    sizes: ["Regular", "Large"],
    material: "Bamboo Fiber",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockUsers: User[] = [
  {
    _id: "user1",
    email: "admin@hijabstore.com",
    password: "hashedpassword",
    firstName: "Admin",
    lastName: "User",
    role: "admin",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "user2",
    email: "customer@example.com",
    password: "hashedpassword",
    firstName: "Sarah",
    lastName: "Ahmed",
    phone: "+1234567890",
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
    },
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockOrders: Order[] = [
  {
    _id: "order1",
    userId: "user2",
    items: [
      {
        productId: "1",
        quantity: 2,
        color: "Black",
        size: "Regular",
        price: 29.99,
      },
      {
        productId: "2",
        quantity: 1,
        color: "White",
        size: "Large",
        price: 19.99,
      },
    ],
    totalAmount: 79.97,
    status: "processing",
    shippingAddress: {
      firstName: "Sarah",
      lastName: "Ahmed",
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
      phone: "+1234567890",
    },
    paymentMethod: "Credit Card",
    paymentStatus: "paid",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
